import type { Metadata } from 'next';

// import { fontName } from '@/app/fonts';
import '@/shared/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      {/* <body className={fontName.className}> */}
      <body>{children}</body>
    </html>
  );
}
