import type { Metadata } from 'next';

import { sCordDream } from '@/app/fonts';

import '@/shared/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={sCordDream.className}>{children}</body>
    </html>
  );
}
