import type { Metadata } from 'next';

import { sCordDream } from '@/app/fonts';

import '@/shared/styles/globals.css';
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko' className={cn("font-sans", geist.variable)}>
      <body className={sCordDream.className}>{children}</body>
    </html>
  );
}
