export const COUNTRIES = [
  {
    id: 288,
    alpha2: 'gh',
    alpha3: 'gha',
    name: '가나',
    continent: '아프리카',
    currency: { code: 'GHS', name: '가나 세디', symbol: '₵' },
  },
  {
    id: 266,
    alpha2: 'ga',
    alpha3: 'gab',
    name: '가봉',
    continent: '아프리카',
    currency: { code: 'XAF', name: 'CFA 프랑', symbol: 'Fr' },
  },
  {
    id: 328,
    alpha2: 'gy',
    alpha3: 'guy',
    name: '가이아나',
    continent: '남아메리카',
    currency: { code: 'GYD', name: '가이아나 달러', symbol: '$' },
  },
  {
    id: 270,
    alpha2: 'gm',
    alpha3: 'gmb',
    name: '감비아',
    continent: '아프리카',
    currency: { code: 'GMD', name: '달라시', symbol: 'D' },
  },
  {
    id: 831,
    alpha2: 'gg',
    alpha3: 'ggy',
    name: '건지섬',
    continent: '기타',
    currency: { code: 'GBP', name: '파운드 스털링', symbol: '£' },
  },
  {
    id: 312,
    alpha2: 'gp',
    alpha3: 'glp',
    name: '과들루프',
    continent: '북아메리카',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 320,
    alpha2: 'gt',
    alpha3: 'gtm',
    name: '과테말라',
    continent: '기타',
    currency: { code: 'GTQ', name: '케찰', symbol: 'Q' },
  },
  {
    id: 316,
    alpha2: 'gu',
    alpha3: 'gum',
    name: '괌',
    continent: '북아메리카',
    currency: { code: 'USD', name: '미국 달러', symbol: '$' },
  },
  {
    id: 308,
    alpha2: 'gd',
    alpha3: 'grd',
    name: '그레나다',
    continent: '북아메리카',
    currency: { code: 'XCD', name: '동카리브 달러', symbol: '$' },
  },
  {
    id: 300,
    alpha2: 'gr',
    alpha3: 'grc',
    name: '그리스',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 304,
    alpha2: 'gl',
    alpha3: 'grl',
    name: '그린란드',
    continent: '북아메리카',
    currency: { code: 'DKK', name: '덴마크 크로네', symbol: 'kr' },
  },
  {
    id: 324,
    alpha2: 'gn',
    alpha3: 'gin',
    name: '기니',
    continent: '아프리카',
    currency: { code: 'GNF', name: '기니 프랑', symbol: 'Fr' },
  },
  {
    id: 624,
    alpha2: 'gw',
    alpha3: 'gnb',
    name: '기니비사우',
    continent: '아프리카',
    currency: { code: 'XOF', name: 'CFA 프랑', symbol: 'Fr' },
  },
  {
    id: 516,
    alpha2: 'na',
    alpha3: 'nam',
    name: '나미비아',
    continent: '아프리카',
    currency: { code: 'NAD', name: '나미비아 달러', symbol: '$' },
  },
  {
    id: 520,
    alpha2: 'nr',
    alpha3: 'nru',
    name: '나우루',
    continent: '오세아니아',
    currency: { code: 'AUD', name: '호주 달러', symbol: 'A$' },
  },
  {
    id: 566,
    alpha2: 'ng',
    alpha3: 'nga',
    name: '나이지리아',
    continent: '아프리카',
    currency: { code: 'NGN', name: '나이라', symbol: '₦' },
  },
  {
    id: 10,
    alpha2: 'aq',
    alpha3: 'ata',
    name: '남극',
    continent: '남극',
    currency: { code: '-', name: '해당없음', symbol: '-' },
  },
  {
    id: 728,
    alpha2: 'ss',
    alpha3: 'ssd',
    name: '남수단',
    continent: '기타',
    currency: { code: 'SSP', name: '남수단 파운드', symbol: '£' },
  },
  {
    id: 710,
    alpha2: 'za',
    alpha3: 'zaf',
    name: '남아프리카 공화국',
    continent: '아프리카',
    currency: { code: 'ZAR', name: '랜드', symbol: 'R' },
  },
  {
    id: 528,
    alpha2: 'nl',
    alpha3: 'nld',
    name: '네덜란드',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 524,
    alpha2: 'np',
    alpha3: 'npl',
    name: '네팔',
    continent: '아시아',
    currency: { code: 'NPR', name: '네팔 루피', symbol: '₨' },
  },
  {
    id: 578,
    alpha2: 'no',
    alpha3: 'nor',
    name: '노르웨이',
    continent: '유럽',
    currency: { code: 'NOK', name: '노르웨이 크로네', symbol: 'kr' },
  },
  {
    id: 574,
    alpha2: 'nf',
    alpha3: 'nfk',
    name: '노퍽섬',
    continent: '기타',
    currency: { code: 'AUD', name: '호주 달러', symbol: 'A$' },
  },
  {
    id: 540,
    alpha2: 'nc',
    alpha3: 'ncl',
    name: '누벨칼레도니',
    continent: '기타',
    currency: { code: 'XPF', name: 'CFP 프랑', symbol: 'Fr' },
  },
  {
    id: 554,
    alpha2: 'nz',
    alpha3: 'nzl',
    name: '뉴질랜드',
    continent: '오세아니아',
    currency: { code: 'NZD', name: '뉴질랜드 달러', symbol: 'NZ$' },
  },
  {
    id: 570,
    alpha2: 'nu',
    alpha3: 'niu',
    name: '니우에',
    continent: '오세아니아',
    currency: { code: 'NZD', name: '뉴질랜드 달러', symbol: 'NZ$' },
  },
  {
    id: 562,
    alpha2: 'ne',
    alpha3: 'ner',
    name: '니제르',
    continent: '아프리카',
    currency: { code: 'XOF', name: 'CFA 프랑', symbol: 'Fr' },
  },
  {
    id: 558,
    alpha2: 'ni',
    alpha3: 'nic',
    name: '니카라과',
    continent: '기타',
    currency: { code: 'NIO', name: '코르도바', symbol: 'C$' },
  },
  {
    id: 410,
    alpha2: 'kr',
    alpha3: 'kor',
    name: '대한민국',
    continent: '아시아',
    currency: { code: 'KRW', name: '대한민국 원', symbol: '₩' },
  },
  {
    id: 208,
    alpha2: 'dk',
    alpha3: 'dnk',
    name: '덴마크',
    continent: '유럽',
    currency: { code: 'DKK', name: '덴마크 크로네', symbol: 'kr' },
  },
  {
    id: 214,
    alpha2: 'do',
    alpha3: 'dom',
    name: '도미니카 공화국',
    continent: '북아메리카',
    currency: { code: 'DOP', name: '도미니카 페소', symbol: '$' },
  },
  {
    id: 212,
    alpha2: 'dm',
    alpha3: 'dma',
    name: '도미니카 연방',
    continent: '북아메리카',
    currency: { code: 'XCD', name: '동카리브 달러', symbol: '$' },
  },
  {
    id: 276,
    alpha2: 'de',
    alpha3: 'deu',
    name: '독일',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 626,
    alpha2: 'tl',
    alpha3: 'tls',
    name: '동티모르',
    continent: '아시아',
    currency: { code: 'USD', name: '미국 달러', symbol: '$' },
  },
  {
    id: 418,
    alpha2: 'la',
    alpha3: 'lao',
    name: '라오스',
    continent: '아시아',
    currency: { code: 'LAK', name: '킵', symbol: '₭' },
  },
  {
    id: 430,
    alpha2: 'lr',
    alpha3: 'lbr',
    name: '라이베리아',
    continent: '아프리카',
    currency: { code: 'LRD', name: '라이베리아 달러', symbol: '$' },
  },
  {
    id: 428,
    alpha2: 'lv',
    alpha3: 'lva',
    name: '라트비아',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 643,
    alpha2: 'ru',
    alpha3: 'rus',
    name: '러시아',
    continent: '유럽',
    currency: { code: 'RUB', name: '루블', symbol: '₽' },
  },
  {
    id: 422,
    alpha2: 'lb',
    alpha3: 'lbn',
    name: '레바논',
    continent: '아시아',
    currency: { code: 'LBP', name: '레바논 파운드', symbol: 'ل.ل' },
  },
  {
    id: 426,
    alpha2: 'ls',
    alpha3: 'lso',
    name: '레소토',
    continent: '아프리카',
    currency: { code: 'LSL', name: '로티', symbol: 'L' },
  },
  {
    id: 638,
    alpha2: 're',
    alpha3: 'reu',
    name: '레위니옹',
    continent: '기타',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 642,
    alpha2: 'ro',
    alpha3: 'rou',
    name: '루마니아',
    continent: '유럽',
    currency: { code: 'RON', name: '루마니아 레우', symbol: 'lei' },
  },
  {
    id: 442,
    alpha2: 'lu',
    alpha3: 'lux',
    name: '룩셈부르크',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 646,
    alpha2: 'rw',
    alpha3: 'rwa',
    name: '르완다',
    continent: '아프리카',
    currency: { code: 'RWF', name: '르완다 프랑', symbol: 'Fr' },
  },
  {
    id: 434,
    alpha2: 'ly',
    alpha3: 'lby',
    name: '리비아',
    continent: '아프리카',
    currency: { code: 'LYD', name: '리비아 디나르', symbol: 'ل.د' },
  },
  {
    id: 440,
    alpha2: 'lt',
    alpha3: 'ltu',
    name: '리투아니아',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 438,
    alpha2: 'li',
    alpha3: 'lie',
    name: '리히텐슈타인',
    continent: '유럽',
    currency: { code: 'CHF', name: '스위스 프랑', symbol: 'Fr' },
  },
  {
    id: 450,
    alpha2: 'mg',
    alpha3: 'mdg',
    name: '마다가스카르',
    continent: '아프리카',
    currency: { code: 'MGA', name: '아리아리', symbol: 'Ar' },
  },
  {
    id: 474,
    alpha2: 'mq',
    alpha3: 'mtq',
    name: '마르티니크',
    continent: '북아메리카',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 584,
    alpha2: 'mh',
    alpha3: 'mhl',
    name: '마셜 제도',
    continent: '오세아니아',
    currency: { code: 'USD', name: '미국 달러', symbol: '$' },
  },
  {
    id: 175,
    alpha2: 'yt',
    alpha3: 'myt',
    name: '마요트',
    continent: '기타',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 446,
    alpha2: 'mo',
    alpha3: 'mac',
    name: '마카오',
    continent: '아시아',
    currency: { code: 'MOP', name: '파타카', symbol: 'P' },
  },
  {
    id: 807,
    alpha2: 'mk',
    alpha3: 'mkd',
    name: '북마케도니아',
    continent: '유럽',
    currency: { code: 'MKD', name: '마케도니아 데나르', symbol: 'ден' },
  },
  {
    id: 454,
    alpha2: 'mw',
    alpha3: 'mwi',
    name: '말라위',
    continent: '아프리카',
    currency: { code: 'MWK', name: '말라위 콰차', symbol: 'MK' },
  },
  {
    id: 458,
    alpha2: 'my',
    alpha3: 'mys',
    name: '말레이시아',
    continent: '아시아',
    currency: { code: 'MYR', name: '링깃', symbol: 'RM' },
  },
  {
    id: 466,
    alpha2: 'ml',
    alpha3: 'mli',
    name: '말리',
    continent: '아프리카',
    currency: { code: 'XOF', name: 'CFA 프랑', symbol: 'Fr' },
  },
  {
    id: 833,
    alpha2: 'im',
    alpha3: 'imn',
    name: '맨섬',
    continent: '기타',
    currency: { code: 'GBP', name: '파운드 스털링', symbol: '£' },
  },
  {
    id: 484,
    alpha2: 'mx',
    alpha3: 'mex',
    name: '멕시코',
    continent: '북아메리카',
    currency: { code: 'MXN', name: '멕시코 페소', symbol: '$' },
  },
  {
    id: 492,
    alpha2: 'mc',
    alpha3: 'mco',
    name: '모나코',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 504,
    alpha2: 'ma',
    alpha3: 'mar',
    name: '모로코',
    continent: '아프리카',
    currency: { code: 'MAD', name: '모로코 디르함', symbol: 'د.م.' },
  },
  {
    id: 480,
    alpha2: 'mu',
    alpha3: 'mus',
    name: '모리셔스',
    continent: '아프리카',
    currency: { code: 'MUR', name: '모리셔스 루피', symbol: '₨' },
  },
  {
    id: 478,
    alpha2: 'mr',
    alpha3: 'mrt',
    name: '모리타니',
    continent: '아프리카',
    currency: { code: 'MRU', name: '우기야', symbol: 'UM' },
  },
  {
    id: 508,
    alpha2: 'mz',
    alpha3: 'moz',
    name: '모잠비크',
    continent: '아프리카',
    currency: { code: 'MZN', name: '메티칼', symbol: 'MT' },
  },
  {
    id: 499,
    alpha2: 'me',
    alpha3: 'mne',
    name: '몬테네그로',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 500,
    alpha2: 'ms',
    alpha3: 'msr',
    name: '몬트세랫',
    continent: '기타',
    currency: { code: 'XCD', name: '동카리브 달러', symbol: '$' },
  },
  {
    id: 498,
    alpha2: 'md',
    alpha3: 'mda',
    name: '몰도바',
    continent: '유럽',
    currency: { code: 'MDL', name: '몰도바 레우', symbol: 'L' },
  },
  {
    id: 462,
    alpha2: 'mv',
    alpha3: 'mdv',
    name: '몰디브',
    continent: '아시아',
    currency: { code: 'MVR', name: '루피야', symbol: 'Rf' },
  },
  {
    id: 470,
    alpha2: 'mt',
    alpha3: 'mlt',
    name: '몰타',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 496,
    alpha2: 'mn',
    alpha3: 'mng',
    name: '몽골',
    continent: '아시아',
    currency: { code: 'MNT', name: '투그릭', symbol: '₮' },
  },
  {
    id: 840,
    alpha2: 'us',
    alpha3: 'usa',
    name: '미국',
    continent: '북아메리카',
    currency: { code: 'USD', name: '미국 달러', symbol: '$' },
  },
  {
    id: 581,
    alpha2: 'um',
    alpha3: 'umi',
    name: '미국령 군소 제도',
    continent: '기타',
    currency: { code: 'USD', name: '미국 달러', symbol: '$' },
  },
  {
    id: 850,
    alpha2: 'vi',
    alpha3: 'vir',
    name: '미국령 버진아일랜드',
    continent: '북아메리카',
    currency: { code: 'USD', name: '미국 달러', symbol: '$' },
  },
  {
    id: 104,
    alpha2: 'mm',
    alpha3: 'mmr',
    name: '미얀마',
    continent: '아시아',
    currency: { code: 'MMK', name: '짯', symbol: 'K' },
  },
  {
    id: 583,
    alpha2: 'fm',
    alpha3: 'fsm',
    name: '미크로네시아 연방',
    continent: '오세아니아',
    currency: { code: 'USD', name: '미국 달러', symbol: '$' },
  },
  {
    id: 548,
    alpha2: 'vu',
    alpha3: 'vut',
    name: '바누아투',
    continent: '오세아니아',
    currency: { code: 'VUV', name: '바투', symbol: 'Vt' },
  },
  {
    id: 48,
    alpha2: 'bh',
    alpha3: 'bhr',
    name: '바레인',
    continent: '아시아',
    currency: { code: 'BHD', name: '바레인 디나르', symbol: '.د.ب' },
  },
  {
    id: 52,
    alpha2: 'bb',
    alpha3: 'brb',
    name: '바베이도스',
    continent: '북아메리카',
    currency: { code: 'BBD', name: '바베이도스 달러', symbol: '$' },
  },
  {
    id: 336,
    alpha2: 'va',
    alpha3: 'vat',
    name: '바티칸 시국',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 44,
    alpha2: 'bs',
    alpha3: 'bhs',
    name: '바하마',
    continent: '북아메리카',
    currency: { code: 'BSD', name: '바하마 달러', symbol: '$' },
  },
  {
    id: 50,
    alpha2: 'bd',
    alpha3: 'bgd',
    name: '방글라데시',
    continent: '아시아',
    currency: { code: 'BDT', name: '타카', symbol: '৳' },
  },
  {
    id: 60,
    alpha2: 'bm',
    alpha3: 'bmu',
    name: '버뮤다',
    continent: '기타',
    currency: { code: 'BMD', name: '버뮤다 달러', symbol: '$' },
  },
  {
    id: 204,
    alpha2: 'bj',
    alpha3: 'ben',
    name: '베냉',
    continent: '아프리카',
    currency: { code: 'XOF', name: 'CFA 프랑', symbol: 'Fr' },
  },
  {
    id: 862,
    alpha2: 've',
    alpha3: 'ven',
    name: '베네수엘라',
    continent: '남아메리카',
    currency: { code: 'VES', name: '볼리바르 소베라노', symbol: 'Bs.' },
  },
  {
    id: 704,
    alpha2: 'vn',
    alpha3: 'vnm',
    name: '베트남',
    continent: '아시아',
    currency: { code: 'VND', name: '동', symbol: '₫' },
  },
  {
    id: 56,
    alpha2: 'be',
    alpha3: 'bel',
    name: '벨기에',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 112,
    alpha2: 'by',
    alpha3: 'blr',
    name: '벨라루스',
    continent: '유럽',
    currency: { code: 'BYN', name: '벨라루스 루블', symbol: 'Br' },
  },
  {
    id: 84,
    alpha2: 'bz',
    alpha3: 'blz',
    name: '벨리즈',
    continent: '북아메리카',
    currency: { code: 'BZD', name: '벨리즈 달러', symbol: '$' },
  },
  {
    id: 535,
    alpha2: 'bq',
    alpha3: 'bes',
    name: '보네르섬',
    continent: '기타',
    currency: { code: 'USD', name: '미국 달러', symbol: '$' },
  },
  {
    id: 70,
    alpha2: 'ba',
    alpha3: 'bih',
    name: '보스니아 헤르체고비나',
    continent: '유럽',
    currency: { code: 'BAM', name: '태환 마르크', symbol: 'KM' },
  },
  {
    id: 72,
    alpha2: 'bw',
    alpha3: 'bwa',
    name: '보츠와나',
    continent: '아프리카',
    currency: { code: 'BWP', name: '풀라', symbol: 'P' },
  },
  {
    id: 68,
    alpha2: 'bo',
    alpha3: 'bol',
    name: '볼리비아',
    continent: '남아메리카',
    currency: { code: 'BOB', name: '볼리비아노', symbol: 'Bs.' },
  },
  {
    id: 108,
    alpha2: 'bi',
    alpha3: 'bdi',
    name: '부룬디',
    continent: '아프리카',
    currency: { code: 'BIF', name: '부룬디 프랑', symbol: 'Fr' },
  },
  {
    id: 854,
    alpha2: 'bf',
    alpha3: 'bfa',
    name: '부르키나파소',
    continent: '아프리카',
    currency: { code: 'XOF', name: 'CFA 프랑', symbol: 'Fr' },
  },
  {
    id: 74,
    alpha2: 'bv',
    alpha3: 'bvt',
    name: '부베섬',
    continent: '기타',
    currency: { code: 'NOK', name: '노르웨이 크로네', symbol: 'kr' },
  },
  {
    id: 64,
    alpha2: 'bt',
    alpha3: 'btn',
    name: '부탄',
    continent: '아시아',
    currency: { code: 'BTN', name: '눌트럼', symbol: 'Nu' },
  },
  {
    id: 580,
    alpha2: 'mp',
    alpha3: 'mnp',
    name: '북마리아나 제도',
    continent: '북아메리카',
    currency: { code: 'USD', name: '미국 달러', symbol: '$' },
  },
  {
    id: 100,
    alpha2: 'bg',
    alpha3: 'bgr',
    name: '불가리아',
    continent: '유럽',
    currency: { code: 'BGN', name: '불가리아 레프', symbol: 'лв' },
  },
  {
    id: 76,
    alpha2: 'br',
    alpha3: 'bra',
    name: '브라질',
    continent: '남아메리카',
    currency: { code: 'BRL', name: '브라질 레알', symbol: 'R$' },
  },
  {
    id: 96,
    alpha2: 'bn',
    alpha3: 'brn',
    name: '브루나이',
    continent: '아시아',
    currency: { code: 'BND', name: '브루나이 달러', symbol: '$' },
  },
  {
    id: 882,
    alpha2: 'ws',
    alpha3: 'wsm',
    name: '사모아',
    continent: '오세아니아',
    currency: { code: 'WST', name: '탈라', symbol: 'T' },
  },
  {
    id: 682,
    alpha2: 'sa',
    alpha3: 'sau',
    name: '사우디아라비아',
    continent: '아시아',
    currency: { code: 'SAR', name: '사우디 리얄', symbol: '﷼' },
  },
  {
    id: 239,
    alpha2: 'gs',
    alpha3: 'sgs',
    name: '사우스조지아 사우스샌드위치 제도',
    continent: '기타',
    currency: { code: 'GBP', name: '파운드 스털링', symbol: '£' },
  },
  {
    id: 674,
    alpha2: 'sm',
    alpha3: 'smr',
    name: '산마리노',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 678,
    alpha2: 'st',
    alpha3: 'stp',
    name: '상투메 프린시페',
    continent: '아프리카',
    currency: { code: 'STN', name: '도브라', symbol: 'Db' },
  },
  {
    id: 663,
    alpha2: 'mf',
    alpha3: 'maf',
    name: '생마르탱',
    continent: '북아메리카',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 652,
    alpha2: 'bl',
    alpha3: 'blm',
    name: '생바르텔레미',
    continent: '북아메리카',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 666,
    alpha2: 'pm',
    alpha3: 'spm',
    name: '생피에르 미클롱',
    continent: '북아메리카',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 732,
    alpha2: 'eh',
    alpha3: 'esh',
    name: '서사하라',
    continent: '기타',
    currency: { code: 'MAD', name: '모로코 디르함', symbol: 'د.م.' },
  },
  {
    id: 686,
    alpha2: 'sn',
    alpha3: 'sen',
    name: '세네갈',
    continent: '아프리카',
    currency: { code: 'XOF', name: 'CFA 프랑', symbol: 'Fr' },
  },
  {
    id: 688,
    alpha2: 'rs',
    alpha3: 'srb',
    name: '세르비아',
    continent: '유럽',
    currency: { code: 'RSD', name: '세르비아 디나르', symbol: 'дин' },
  },
  {
    id: 690,
    alpha2: 'sc',
    alpha3: 'syc',
    name: '세이셸',
    continent: '아프리카',
    currency: { code: 'SCR', name: '세이셸 루피', symbol: '₨' },
  },
  {
    id: 662,
    alpha2: 'lc',
    alpha3: 'lca',
    name: '세인트루시아',
    continent: '북아메리카',
    currency: { code: 'XCD', name: '동카리브 달러', symbol: '$' },
  },
  {
    id: 670,
    alpha2: 'vc',
    alpha3: 'vct',
    name: '세인트빈센트 그레나딘',
    continent: '북아메리카',
    currency: { code: 'XCD', name: '동카리브 달러', symbol: '$' },
  },
  {
    id: 659,
    alpha2: 'kn',
    alpha3: 'kna',
    name: '세인트키츠 네비스',
    continent: '북아메리카',
    currency: { code: 'XCD', name: '동카리브 달러', symbol: '$' },
  },
  {
    id: 654,
    alpha2: 'sh',
    alpha3: 'shn',
    name: '세인트헬레나',
    continent: '기타',
    currency: { code: 'SHP', name: '세인트헬레나 파운드', symbol: '£' },
  },
  {
    id: 706,
    alpha2: 'so',
    alpha3: 'som',
    name: '소말리아',
    continent: '아프리카',
    currency: { code: 'SOS', name: '소말리아 실링', symbol: 'Sh' },
  },
  {
    id: 90,
    alpha2: 'sb',
    alpha3: 'slb',
    name: '솔로몬 제도',
    continent: '오세아니아',
    currency: { code: 'SBD', name: '솔로몬 제도 달러', symbol: '$' },
  },
  {
    id: 729,
    alpha2: 'sd',
    alpha3: 'sdn',
    name: '수단',
    continent: '아프리카',
    currency: { code: 'SDG', name: '수단 파운드', symbol: '£' },
  },
  {
    id: 740,
    alpha2: 'sr',
    alpha3: 'sur',
    name: '수리남',
    continent: '남아메리카',
    currency: { code: 'SRD', name: '수리남 달러', symbol: '$' },
  },
  {
    id: 144,
    alpha2: 'lk',
    alpha3: 'lka',
    name: '스리랑카',
    continent: '아시아',
    currency: { code: 'LKR', name: '스리랑카 루피', symbol: '₨' },
  },
  {
    id: 744,
    alpha2: 'sj',
    alpha3: 'sjm',
    name: '스발바르 얀마옌',
    continent: '기타',
    currency: { code: 'NOK', name: '노르웨이 크로네', symbol: 'kr' },
  },
  {
    id: 752,
    alpha2: 'se',
    alpha3: 'swe',
    name: '스웨덴',
    continent: '유럽',
    currency: { code: 'SEK', name: '스웨덴 크로나', symbol: 'kr' },
  },
  {
    id: 756,
    alpha2: 'ch',
    alpha3: 'che',
    name: '스위스',
    continent: '유럽',
    currency: { code: 'CHF', name: '스위스 프랑', symbol: 'Fr' },
  },
  {
    id: 724,
    alpha2: 'es',
    alpha3: 'esp',
    name: '스페인',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 703,
    alpha2: 'sk',
    alpha3: 'svk',
    name: '슬로바키아',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 705,
    alpha2: 'si',
    alpha3: 'svn',
    name: '슬로베니아',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 760,
    alpha2: 'sy',
    alpha3: 'syr',
    name: '시리아',
    continent: '아시아',
    currency: { code: 'SYP', name: '시리아 파운드', symbol: '£' },
  },
  {
    id: 694,
    alpha2: 'sl',
    alpha3: 'sle',
    name: '시에라리온',
    continent: '아프리카',
    currency: { code: 'SLL', name: '레온', symbol: 'Le' },
  },
  {
    id: 534,
    alpha2: 'sx',
    alpha3: 'sxm',
    name: '신트마르턴',
    continent: '기타',
    currency: { code: 'ANG', name: '네덜란드령 안틸레스 길더', symbol: 'ƒ' },
  },
  {
    id: 702,
    alpha2: 'sg',
    alpha3: 'sgp',
    name: '싱가포르',
    continent: '아시아',
    currency: { code: 'SGD', name: '싱가포르 달러', symbol: 'S$' },
  },
  {
    id: 784,
    alpha2: 'ae',
    alpha3: 'are',
    name: '아랍에미리트',
    continent: '아시아',
    currency: { code: 'AED', name: '디르함', symbol: 'د.إ' },
  },
  {
    id: 533,
    alpha2: 'aw',
    alpha3: 'abw',
    name: '아루바',
    continent: '기타',
    currency: { code: 'AWG', name: '아루바 플로린', symbol: 'ƒ' },
  },
  {
    id: 51,
    alpha2: 'am',
    alpha3: 'arm',
    name: '아르메니아',
    continent: '아시아',
    currency: { code: 'AMD', name: '드람', symbol: '֏' },
  },
  {
    id: 32,
    alpha2: 'ar',
    alpha3: 'arg',
    name: '아르헨티나',
    continent: '남아메리카',
    currency: { code: 'ARS', name: '아르헨티나 페소', symbol: '$' },
  },
  {
    id: 16,
    alpha2: 'as',
    alpha3: 'asm',
    name: '아메리칸사모아',
    continent: '기타',
    currency: { code: 'USD', name: '미국 달러', symbol: '$' },
  },
  {
    id: 352,
    alpha2: 'is',
    alpha3: 'isl',
    name: '아이슬란드',
    continent: '유럽',
    currency: { code: 'ISK', name: '아이슬란드 크로나', symbol: 'kr' },
  },
  {
    id: 332,
    alpha2: 'ht',
    alpha3: 'hti',
    name: '아이티',
    continent: '북아메리카',
    currency: { code: 'HTG', name: '구르드', symbol: 'G' },
  },
  {
    id: 372,
    alpha2: 'ie',
    alpha3: 'irl',
    name: '아일랜드',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 31,
    alpha2: 'az',
    alpha3: 'aze',
    name: '아제르바이잔',
    continent: '아시아',
    currency: { code: 'AZN', name: '마나트', symbol: '₼' },
  },
  {
    id: 4,
    alpha2: 'af',
    alpha3: 'afg',
    name: '아프가니스탄',
    continent: '아시아',
    currency: { code: 'AFN', name: '아프가니', symbol: '؋' },
  },
  {
    id: 20,
    alpha2: 'ad',
    alpha3: 'and',
    name: '안도라',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 8,
    alpha2: 'al',
    alpha3: 'alb',
    name: '알바니아',
    continent: '유럽',
    currency: { code: 'ALL', name: '레크', symbol: 'L' },
  },
  {
    id: 12,
    alpha2: 'dz',
    alpha3: 'dza',
    name: '알제리',
    continent: '아프리카',
    currency: { code: 'DZD', name: '알제리 디나르', symbol: 'د.ج' },
  },
  {
    id: 24,
    alpha2: 'ao',
    alpha3: 'ago',
    name: '앙골라',
    continent: '아프리카',
    currency: { code: 'AOA', name: '콴자', symbol: 'Kz' },
  },
  {
    id: 28,
    alpha2: 'ag',
    alpha3: 'atg',
    name: '앤티가 바부다',
    continent: '북아메리카',
    currency: { code: 'XCD', name: '동카리브 달러', symbol: '$' },
  },
  {
    id: 660,
    alpha2: 'ai',
    alpha3: 'aia',
    name: '앵귈라',
    continent: '북아메리카',
    currency: { code: 'XCD', name: '동카리브 달러', symbol: '$' },
  },
  {
    id: 232,
    alpha2: 'er',
    alpha3: 'eri',
    name: '에리트레아',
    continent: '아프리카',
    currency: { code: 'ERN', name: '낙파', symbol: 'Nfk' },
  },
  {
    id: 748,
    alpha2: 'sz',
    alpha3: 'swz',
    name: '에스와티니',
    continent: '아프리카',
    currency: { code: 'SZL', name: '릴랑게니', symbol: 'L' },
  },
  {
    id: 233,
    alpha2: 'ee',
    alpha3: 'est',
    name: '에스토니아',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 218,
    alpha2: 'ec',
    alpha3: 'ecu',
    name: '에콰도르',
    continent: '남아메리카',
    currency: { code: 'USD', name: '미국 달러', symbol: '$' },
  },
  {
    id: 231,
    alpha2: 'et',
    alpha3: 'eth',
    name: '에티오피아',
    continent: '아프리카',
    currency: { code: 'ETB', name: '비르', symbol: 'Br' },
  },
  {
    id: 222,
    alpha2: 'sv',
    alpha3: 'slv',
    name: '엘살바도르',
    continent: '북아메리카',
    currency: { code: 'USD', name: '미국 달러', symbol: '$' },
  },
  {
    id: 826,
    alpha2: 'gb',
    alpha3: 'gbr',
    name: '영국',
    continent: '유럽',
    currency: { code: 'GBP', name: '파운드 스털링', symbol: '£' },
  },
  {
    id: 92,
    alpha2: 'vg',
    alpha3: 'vgb',
    name: '영국령 버진아일랜드',
    continent: '북아메리카',
    currency: { code: 'USD', name: '미국 달러', symbol: '$' },
  },
  {
    id: 86,
    alpha2: 'io',
    alpha3: 'iot',
    name: '영국령 인도양 지역',
    continent: '기타',
    currency: { code: 'USD', name: '미국 달러', symbol: '$' },
  },
  {
    id: 887,
    alpha2: 'ye',
    alpha3: 'yem',
    name: '예멘',
    continent: '아시아',
    currency: { code: 'YER', name: '예멘 리알', symbol: '﷼' },
  },
  {
    id: 512,
    alpha2: 'om',
    alpha3: 'omn',
    name: '오만',
    continent: '아시아',
    currency: { code: 'OMR', name: '오만 리알', symbol: '﷼' },
  },
  {
    id: 36,
    alpha2: 'au',
    alpha3: 'aus',
    name: '오스트레일리아',
    continent: '오세아니아',
    currency: { code: 'AUD', name: '호주 달러', symbol: 'A$' },
  },
  {
    id: 40,
    alpha2: 'at',
    alpha3: 'aut',
    name: '오스트리아',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 340,
    alpha2: 'hn',
    alpha3: 'hnd',
    name: '온두라스',
    continent: '북아메리카',
    currency: { code: 'HNL', name: '렘피라', symbol: 'L' },
  },
  {
    id: 248,
    alpha2: 'ax',
    alpha3: 'ala',
    name: '올란드 제도',
    continent: '기타',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 400,
    alpha2: 'jo',
    alpha3: 'jor',
    name: '요르단',
    continent: '아시아',
    currency: { code: 'JOD', name: '요르단 디나르', symbol: 'د.ا' },
  },
  {
    id: 800,
    alpha2: 'ug',
    alpha3: 'uga',
    name: '우간다',
    continent: '아프리카',
    currency: { code: 'UGX', name: '우간다 실링', symbol: 'Sh' },
  },
  {
    id: 858,
    alpha2: 'uy',
    alpha3: 'ury',
    name: '우루과이',
    continent: '남아메리카',
    currency: { code: 'UYU', name: '우루과이 페소', symbol: '$' },
  },
  {
    id: 860,
    alpha2: 'uz',
    alpha3: 'uzb',
    name: '우즈베키스탄',
    continent: '아시아',
    currency: { code: 'UZS', name: '숨', symbol: 'сўм' },
  },
  {
    id: 804,
    alpha2: 'ua',
    alpha3: 'ukr',
    name: '우크라이나',
    continent: '유럽',
    currency: { code: 'UAH', name: '흐리우냐', symbol: '₴' },
  },
  {
    id: 876,
    alpha2: 'wf',
    alpha3: 'wlf',
    name: '왈리스 푸투나',
    continent: '기타',
    currency: { code: 'XPF', name: 'CFP 프랑', symbol: 'Fr' },
  },
  {
    id: 368,
    alpha2: 'iq',
    alpha3: 'irq',
    name: '이라크',
    continent: '아시아',
    currency: { code: 'IQD', name: '이라크 디나르', symbol: 'ع.د' },
  },
  {
    id: 364,
    alpha2: 'ir',
    alpha3: 'irn',
    name: '이란',
    continent: '아시아',
    currency: { code: 'IRR', name: '이란 리알', symbol: '﷼' },
  },
  {
    id: 376,
    alpha2: 'il',
    alpha3: 'isr',
    name: '이스라엘',
    continent: '아시아',
    currency: { code: 'ILS', name: '새 셰켈', symbol: '₪' },
  },
  {
    id: 818,
    alpha2: 'eg',
    alpha3: 'egy',
    name: '이집트',
    continent: '아프리카',
    currency: { code: 'EGP', name: '이집트 파운드', symbol: '£' },
  },
  {
    id: 380,
    alpha2: 'it',
    alpha3: 'ita',
    name: '이탈리아',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 356,
    alpha2: 'in',
    alpha3: 'ind',
    name: '인도',
    continent: '아시아',
    currency: { code: 'INR', name: '인도 루피', symbol: '₹' },
  },
  {
    id: 360,
    alpha2: 'id',
    alpha3: 'idn',
    name: '인도네시아',
    continent: '아시아',
    currency: { code: 'IDR', name: '루피아', symbol: 'Rp' },
  },
  {
    id: 392,
    alpha2: 'jp',
    alpha3: 'jpn',
    name: '일본',
    continent: '아시아',
    currency: { code: 'JPY', name: '엔', symbol: '¥' },
  },
  {
    id: 388,
    alpha2: 'jm',
    alpha3: 'jam',
    name: '자메이카',
    continent: '북아메리카',
    currency: { code: 'JMD', name: '자메이카 달러', symbol: '$' },
  },
  {
    id: 894,
    alpha2: 'zm',
    alpha3: 'zmb',
    name: '잠비아',
    continent: '아프리카',
    currency: { code: 'ZMW', name: '잠비아 콰차', symbol: 'ZK' },
  },
  {
    id: 832,
    alpha2: 'je',
    alpha3: 'jey',
    name: '저지섬',
    continent: '기타',
    currency: { code: 'GBP', name: '파운드 스털링', symbol: '£' },
  },
  {
    id: 226,
    alpha2: 'gq',
    alpha3: 'gnq',
    name: '적도 기니',
    continent: '아프리카',
    currency: { code: 'XAF', name: 'CFA 프랑', symbol: 'Fr' },
  },
  {
    id: 408,
    alpha2: 'kp',
    alpha3: 'prk',
    name: '조선민주주의인민공화국',
    continent: '아시아',
    currency: { code: 'KPW', name: '북한 원', symbol: '₩' },
  },
  {
    id: 268,
    alpha2: 'ge',
    alpha3: 'geo',
    name: '조지아',
    continent: '아시아',
    currency: { code: 'GEL', name: '라리', symbol: '₾' },
  },
  {
    id: 156,
    alpha2: 'cn',
    alpha3: 'chn',
    name: '중국',
    continent: '아시아',
    currency: { code: 'CNY', name: '위안', symbol: '¥' },
  },
  {
    id: 140,
    alpha2: 'cf',
    alpha3: 'caf',
    name: '중앙아프리카 공화국',
    continent: '아프리카',
    currency: { code: 'XAF', name: 'CFA 프랑', symbol: 'Fr' },
  },
  {
    id: 262,
    alpha2: 'dj',
    alpha3: 'dji',
    name: '지부티',
    continent: '아프리카',
    currency: { code: 'DJF', name: '지부티 프랑', symbol: 'Fr' },
  },
  {
    id: 292,
    alpha2: 'gi',
    alpha3: 'gib',
    name: '지브롤터',
    continent: '기타',
    currency: { code: 'GIP', name: '지브롤터 파운드', symbol: '£' },
  },
  {
    id: 716,
    alpha2: 'zw',
    alpha3: 'zwe',
    name: '짐바브웨',
    continent: '아프리카',
    currency: { code: 'ZWL', name: '짐바브웨 달러', symbol: '$' },
  },
  {
    id: 148,
    alpha2: 'td',
    alpha3: 'tcd',
    name: '차드',
    continent: '아프리카',
    currency: { code: 'XAF', name: 'CFA 프랑', symbol: 'Fr' },
  },
  {
    id: 203,
    alpha2: 'cz',
    alpha3: 'cze',
    name: '체코',
    continent: '유럽',
    currency: { code: 'CZK', name: '체코 코루나', symbol: 'Kč' },
  },
  {
    id: 152,
    alpha2: 'cl',
    alpha3: 'chl',
    name: '칠레',
    continent: '남아메리카',
    currency: { code: 'CLP', name: '칠레 페소', symbol: '$' },
  },
  {
    id: 120,
    alpha2: 'cm',
    alpha3: 'cmr',
    name: '카메룬',
    continent: '아프리카',
    currency: { code: 'XAF', name: 'CFA 프랑', symbol: 'Fr' },
  },
  {
    id: 132,
    alpha2: 'cv',
    alpha3: 'cpv',
    name: '카보베르데',
    continent: '아프리카',
    currency: { code: 'CVE', name: '카보베르데 에스쿠도', symbol: '$' },
  },
  {
    id: 398,
    alpha2: 'kz',
    alpha3: 'kaz',
    name: '카자흐스탄',
    continent: '아시아',
    currency: { code: 'KZT', name: '텡게', symbol: '₸' },
  },
  {
    id: 634,
    alpha2: 'qa',
    alpha3: 'qat',
    name: '카타르',
    continent: '아시아',
    currency: { code: 'QAR', name: '카타르 리얄', symbol: '﷼' },
  },
  {
    id: 116,
    alpha2: 'kh',
    alpha3: 'khm',
    name: '캄보디아',
    continent: '아시아',
    currency: { code: 'KHR', name: '리엘', symbol: '៛' },
  },
  {
    id: 124,
    alpha2: 'ca',
    alpha3: 'can',
    name: '캐나다',
    continent: '북아메리카',
    currency: { code: 'CAD', name: '캐나다 달러', symbol: 'C$' },
  },
  {
    id: 404,
    alpha2: 'ke',
    alpha3: 'ken',
    name: '케냐',
    continent: '아프리카',
    currency: { code: 'KES', name: '케냐 실링', symbol: 'KSh' },
  },
  {
    id: 136,
    alpha2: 'ky',
    alpha3: 'cym',
    name: '케이맨 제도',
    continent: '북아메리카',
    currency: { code: 'KYD', name: '케이맨 제도 달러', symbol: '$' },
  },
  {
    id: 174,
    alpha2: 'km',
    alpha3: 'com',
    name: '코모로',
    continent: '아프리카',
    currency: { code: 'KMF', name: '코모로 프랑', symbol: 'Fr' },
  },
  {
    id: 188,
    alpha2: 'cr',
    alpha3: 'cri',
    name: '코스타리카',
    continent: '북아메리카',
    currency: { code: 'CRC', name: '콜론', symbol: '₡' },
  },
  {
    id: 166,
    alpha2: 'cc',
    alpha3: 'cck',
    name: '코코스 제도',
    continent: '기타',
    currency: { code: 'AUD', name: '호주 달러', symbol: 'A$' },
  },
  {
    id: 384,
    alpha2: 'ci',
    alpha3: 'civ',
    name: '코트디부아르',
    continent: '아프리카',
    currency: { code: 'XOF', name: 'CFA 프랑', symbol: 'Fr' },
  },
  {
    id: 170,
    alpha2: 'co',
    alpha3: 'col',
    name: '콜롬비아',
    continent: '남아메리카',
    currency: { code: 'COP', name: '콜롬비아 페소', symbol: '$' },
  },
  {
    id: 178,
    alpha2: 'cg',
    alpha3: 'cog',
    name: '콩고 공화국',
    continent: '아프리카',
    currency: { code: 'XAF', name: 'CFA 프랑', symbol: 'Fr' },
  },
  {
    id: 180,
    alpha2: 'cd',
    alpha3: 'cod',
    name: '콩고 민주 공화국',
    continent: '아프리카',
    currency: { code: 'CDF', name: '콩고 프랑', symbol: 'Fr' },
  },
  {
    id: 192,
    alpha2: 'cu',
    alpha3: 'cub',
    name: '쿠바',
    continent: '북아메리카',
    currency: { code: 'CUP', name: '쿠바 페소', symbol: '$' },
  },
  {
    id: 414,
    alpha2: 'kw',
    alpha3: 'kwt',
    name: '쿠웨이트',
    continent: '아시아',
    currency: { code: 'KWD', name: '쿠웨이트 디나르', symbol: 'د.ك' },
  },
  {
    id: 184,
    alpha2: 'ck',
    alpha3: 'cok',
    name: '쿡 제도',
    continent: '오세아니아',
    currency: { code: 'NZD', name: '뉴질랜드 달러', symbol: 'NZ$' },
  },
  {
    id: 531,
    alpha2: 'cw',
    alpha3: 'cuw',
    name: '퀴라소',
    continent: '기타',
    currency: { code: 'ANG', name: '네덜란드령 안틸레스 길더', symbol: 'ƒ' },
  },
  {
    id: 191,
    alpha2: 'hr',
    alpha3: 'hrv',
    name: '크로아티아',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 162,
    alpha2: 'cx',
    alpha3: 'cxr',
    name: '크리스마스섬',
    continent: '기타',
    currency: { code: 'AUD', name: '호주 달러', symbol: 'A$' },
  },
  {
    id: 417,
    alpha2: 'kg',
    alpha3: 'kgz',
    name: '키르기스스탄',
    continent: '아시아',
    currency: { code: 'KGS', name: '솜', symbol: 'с' },
  },
  {
    id: 296,
    alpha2: 'ki',
    alpha3: 'kir',
    name: '키리바시',
    continent: '오세아니아',
    currency: { code: 'AUD', name: '호주 달러', symbol: 'A$' },
  },
  {
    id: 196,
    alpha2: 'cy',
    alpha3: 'cyp',
    name: '키프로스',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 158,
    alpha2: 'tw',
    alpha3: 'twn',
    name: '대만',
    continent: '아시아',
    currency: { code: 'TWD', name: '신 대만 달러', symbol: 'NT$' },
  },
  {
    id: 762,
    alpha2: 'tj',
    alpha3: 'tjk',
    name: '타지키스탄',
    continent: '아시아',
    currency: { code: 'TJS', name: '소모니', symbol: 'SM' },
  },
  {
    id: 834,
    alpha2: 'tz',
    alpha3: 'tza',
    name: '탄자니아',
    continent: '아프리카',
    currency: { code: 'TZS', name: '탄자니아 실링', symbol: 'Sh' },
  },
  {
    id: 764,
    alpha2: 'th',
    alpha3: 'tha',
    name: '태국',
    continent: '아시아',
    currency: { code: 'THB', name: '바트', symbol: '฿' },
  },
  {
    id: 796,
    alpha2: 'tc',
    alpha3: 'tca',
    name: '터크스 케이커스 제도',
    continent: '북아메리카',
    currency: { code: 'USD', name: '미국 달러', symbol: '$' },
  },
  {
    id: 792,
    alpha2: 'tr',
    alpha3: 'tur',
    name: '튀르키예',
    continent: '아시아',
    currency: { code: 'TRY', name: '튀르키예 리라', symbol: '₺' },
  },
  {
    id: 768,
    alpha2: 'tg',
    alpha3: 'tgo',
    name: '토고',
    continent: '아프리카',
    currency: { code: 'XOF', name: 'CFA 프랑', symbol: 'Fr' },
  },
  {
    id: 772,
    alpha2: 'tk',
    alpha3: 'tkl',
    name: '토켈라우',
    continent: '기타',
    currency: { code: 'NZD', name: '뉴질랜드 달러', symbol: 'NZ$' },
  },
  {
    id: 776,
    alpha2: 'to',
    alpha3: 'ton',
    name: '통가',
    continent: '오세아니아',
    currency: { code: 'TOP', name: '파앙가', symbol: 'T$' },
  },
  {
    id: 795,
    alpha2: 'tm',
    alpha3: 'tkm',
    name: '투르크메니스탄',
    continent: '아시아',
    currency: { code: 'TMT', name: '마나트', symbol: 'T' },
  },
  {
    id: 798,
    alpha2: 'tv',
    alpha3: 'tuv',
    name: '투발루',
    continent: '오세아니아',
    currency: { code: 'AUD', name: '호주 달러', symbol: 'A$' },
  },
  {
    id: 788,
    alpha2: 'tn',
    alpha3: 'tun',
    name: '튀니지',
    continent: '아프리카',
    currency: { code: 'TND', name: '튀니지 디나르', symbol: 'د.ت' },
  },
  {
    id: 780,
    alpha2: 'tt',
    alpha3: 'tto',
    name: '트리니다드 토바고',
    continent: '기타',
    currency: { code: 'TTD', name: '트리니다드 토바고 달러', symbol: '$' },
  },
  {
    id: 591,
    alpha2: 'pa',
    alpha3: 'pan',
    name: '파나마',
    continent: '북아메리카',
    currency: { code: 'PAB', name: '발보아', symbol: 'B/.' },
  },
  {
    id: 600,
    alpha2: 'py',
    alpha3: 'pry',
    name: '파라과이',
    continent: '남아메리카',
    currency: { code: 'PYG', name: '과라니', symbol: '₲' },
  },
  {
    id: 586,
    alpha2: 'pk',
    alpha3: 'pak',
    name: '파키스탄',
    continent: '아시아',
    currency: { code: 'PKR', name: '파키스탄 루피', symbol: '₨' },
  },
  {
    id: 598,
    alpha2: 'pg',
    alpha3: 'png',
    name: '파푸아뉴기니',
    continent: '오세아니아',
    currency: { code: 'PGK', name: '키나', symbol: 'K' },
  },
  {
    id: 585,
    alpha2: 'pw',
    alpha3: 'plw',
    name: '팔라우',
    continent: '오세아니아',
    currency: { code: 'USD', name: '미국 달러', symbol: '$' },
  },
  {
    id: 275,
    alpha2: 'ps',
    alpha3: 'pse',
    name: '팔레스타인',
    continent: '기타',
    currency: { code: 'ILS', name: '새 셰켈', symbol: '₪' },
  },
  {
    id: 234,
    alpha2: 'fo',
    alpha3: 'fro',
    name: '페로 제도',
    continent: '기타',
    currency: { code: 'DKK', name: '덴마크 크로네', symbol: 'kr' },
  },
  {
    id: 604,
    alpha2: 'pe',
    alpha3: 'per',
    name: '페루',
    continent: '남아메리카',
    currency: { code: 'PEN', name: '솔', symbol: 'S/.' },
  },
  {
    id: 620,
    alpha2: 'pt',
    alpha3: 'prt',
    name: '포르투갈',
    continent: '기타',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 238,
    alpha2: 'fk',
    alpha3: 'flk',
    name: '포클랜드 제도',
    continent: '기타',
    currency: { code: 'FKP', name: '포클랜드 파운드', symbol: '£' },
  },
  {
    id: 616,
    alpha2: 'pl',
    alpha3: 'pol',
    name: '폴란드',
    continent: '유럽',
    currency: { code: 'PLN', name: '즈워티', symbol: 'zł' },
  },
  {
    id: 630,
    alpha2: 'pr',
    alpha3: 'pri',
    name: '푸에르토리코',
    continent: '북아메리카',
    currency: { code: 'USD', name: '미국 달러', symbol: '$' },
  },
  {
    id: 250,
    alpha2: 'fr',
    alpha3: 'fra',
    name: '프랑스',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 254,
    alpha2: 'gf',
    alpha3: 'guf',
    name: '프랑스령 기아나',
    continent: '남아메리카',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 260,
    alpha2: 'tf',
    alpha3: 'atf',
    name: '프랑스령 남방 및 남극 지역',
    continent: '기타',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 258,
    alpha2: 'pf',
    alpha3: 'pyf',
    name: '프랑스령 폴리네시아',
    continent: '기타',
    currency: { code: 'XPF', name: 'CFP 프랑', symbol: 'Fr' },
  },
  {
    id: 242,
    alpha2: 'fj',
    alpha3: 'fji',
    name: '피지',
    continent: '오세아니아',
    currency: { code: 'FJD', name: '피지 달러', symbol: '$' },
  },
  {
    id: 246,
    alpha2: 'fi',
    alpha3: 'fin',
    name: '핀란드',
    continent: '유럽',
    currency: { code: 'EUR', name: '유로', symbol: '€' },
  },
  {
    id: 608,
    alpha2: 'ph',
    alpha3: 'phl',
    name: '필리핀',
    continent: '아시아',
    currency: { code: 'PHP', name: '필리핀 페소', symbol: '₱' },
  },
  {
    id: 612,
    alpha2: 'pn',
    alpha3: 'pcn',
    name: '핏케언 제도',
    continent: '기타',
    currency: { code: 'NZD', name: '뉴질랜드 달러', symbol: 'NZ$' },
  },
  {
    id: 334,
    alpha2: 'hm',
    alpha3: 'hmd',
    name: '허드 맥도널드 제도',
    continent: '기타',
    currency: { code: 'AUD', name: '호주 달러', symbol: 'A$' },
  },
  {
    id: 348,
    alpha2: 'hu',
    alpha3: 'hun',
    name: '헝가리',
    continent: '유럽',
    currency: { code: 'HUF', name: '포린트', symbol: 'Ft' },
  },
  {
    id: 344,
    alpha2: 'hk',
    alpha3: 'hkg',
    name: '홍콩',
    continent: '아시아',
    currency: { code: 'HKD', name: '홍콩 달러', symbol: 'HK$' },
  },
];

// 타입
export type Country = (typeof COUNTRIES)[number];
export type Currency = Country['currency'];
