// 국내 - 검색용 정적 데이터
export const KOREA_REGIONS = [
  {
    name: '서울',
    code: '11',
    type: 'province',
    parent: null,
  },
  {
    name: '서울 - 종로구',
    code: '010',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 중구',
    code: '020',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 용산구',
    code: '030',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 성동구',
    code: '040',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 광진구',
    code: '050',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 동대문구',
    code: '060',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 중랑구',
    code: '070',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 성북구',
    code: '080',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 강북구',
    code: '090',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 도봉구',
    code: '100',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 노원구',
    code: '110',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 은평구',
    code: '120',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 서대문구',
    code: '130',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 마포구',
    code: '140',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 양천구',
    code: '150',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 강서구',
    code: '160',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 구로구',
    code: '170',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 금천구',
    code: '180',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 영등포구',
    code: '190',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 동작구',
    code: '200',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 관악구',
    code: '210',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 서초구',
    code: '220',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 강남구',
    code: '230',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 송파구',
    code: '240',
    type: 'city',
    parent: '서울',
  },
  {
    name: '서울 - 강동구',
    code: '250',
    type: 'city',
    parent: '서울',
  },
  {
    name: '부산',
    code: '21',
    type: 'province',
    parent: null,
  },
  {
    name: '부산 - 중구',
    code: '010',
    type: 'city',
    parent: '부산',
  },
  {
    name: '부산 - 서구',
    code: '020',
    type: 'city',
    parent: '부산',
  },
  {
    name: '부산 - 동구',
    code: '030',
    type: 'city',
    parent: '부산',
  },
  {
    name: '부산 - 영도구',
    code: '040',
    type: 'city',
    parent: '부산',
  },
  {
    name: '부산 - 부산진구',
    code: '050',
    type: 'city',
    parent: '부산',
  },
  {
    name: '부산 - 동래구',
    code: '060',
    type: 'city',
    parent: '부산',
  },
  {
    name: '부산 - 남구',
    code: '070',
    type: 'city',
    parent: '부산',
  },
  {
    name: '부산 - 북구',
    code: '080',
    type: 'city',
    parent: '부산',
  },
  {
    name: '부산 - 해운대구',
    code: '090',
    type: 'city',
    parent: '부산',
  },
  {
    name: '부산 - 사하구',
    code: '100',
    type: 'city',
    parent: '부산',
  },
  {
    name: '부산 - 금정구',
    code: '110',
    type: 'city',
    parent: '부산',
  },
  {
    name: '부산 - 강서구',
    code: '120',
    type: 'city',
    parent: '부산',
  },
  {
    name: '부산 - 연제구',
    code: '130',
    type: 'city',
    parent: '부산',
  },
  {
    name: '부산 - 수영구',
    code: '140',
    type: 'city',
    parent: '부산',
  },
  {
    name: '부산 - 사상구',
    code: '150',
    type: 'city',
    parent: '부산',
  },
  {
    name: '부산 - 기장군',
    code: '510',
    type: 'city',
    parent: '부산',
  },
  {
    name: '대구',
    code: '22',
    type: 'province',
    parent: null,
  },
  {
    name: '대구 - 중구',
    code: '010',
    type: 'city',
    parent: '대구',
  },
  {
    name: '대구 - 동구',
    code: '020',
    type: 'city',
    parent: '대구',
  },
  {
    name: '대구 - 서구',
    code: '030',
    type: 'city',
    parent: '대구',
  },
  {
    name: '대구 - 남구',
    code: '040',
    type: 'city',
    parent: '대구',
  },
  {
    name: '대구 - 북구',
    code: '050',
    type: 'city',
    parent: '대구',
  },
  {
    name: '대구 - 수성구',
    code: '060',
    type: 'city',
    parent: '대구',
  },
  {
    name: '대구 - 달서구',
    code: '070',
    type: 'city',
    parent: '대구',
  },
  {
    name: '대구 - 달성군',
    code: '510',
    type: 'city',
    parent: '대구',
  },
  {
    name: '대구 - 군위군',
    code: '520',
    type: 'city',
    parent: '대구',
  },
  {
    name: '인천',
    code: '23',
    type: 'province',
    parent: null,
  },
  {
    name: '인천 - 중구',
    code: '010',
    type: 'city',
    parent: '인천',
  },
  {
    name: '인천 - 동구',
    code: '020',
    type: 'city',
    parent: '인천',
  },
  {
    name: '인천 - 연수구',
    code: '040',
    type: 'city',
    parent: '인천',
  },
  {
    name: '인천 - 남동구',
    code: '050',
    type: 'city',
    parent: '인천',
  },
  {
    name: '인천 - 부평구',
    code: '060',
    type: 'city',
    parent: '인천',
  },
  {
    name: '인천 - 계양구',
    code: '070',
    type: 'city',
    parent: '인천',
  },
  {
    name: '인천 - 서구',
    code: '080',
    type: 'city',
    parent: '인천',
  },
  {
    name: '인천 - 미추홀구',
    code: '090',
    type: 'city',
    parent: '인천',
  },
  {
    name: '인천 - 강화군',
    code: '510',
    type: 'city',
    parent: '인천',
  },
  {
    name: '인천 - 옹진군',
    code: '520',
    type: 'city',
    parent: '인천',
  },
  {
    name: '광주',
    code: '24',
    type: 'province',
    parent: null,
  },
  {
    name: '광주 - 동구',
    code: '010',
    type: 'city',
    parent: '광주',
  },
  {
    name: '광주 - 서구',
    code: '020',
    type: 'city',
    parent: '광주',
  },
  {
    name: '광주 - 남구',
    code: '030',
    type: 'city',
    parent: '광주',
  },
  {
    name: '광주 - 북구',
    code: '040',
    type: 'city',
    parent: '광주',
  },
  {
    name: '광주 - 광산구',
    code: '050',
    type: 'city',
    parent: '광주',
  },
  {
    name: '대전',
    code: '25',
    type: 'province',
    parent: null,
  },
  {
    name: '대전 - 동구',
    code: '010',
    type: 'city',
    parent: '대전',
  },
  {
    name: '대전 - 중구',
    code: '020',
    type: 'city',
    parent: '대전',
  },
  {
    name: '대전 - 서구',
    code: '030',
    type: 'city',
    parent: '대전',
  },
  {
    name: '대전 - 유성구',
    code: '040',
    type: 'city',
    parent: '대전',
  },
  {
    name: '대전 - 대덕구',
    code: '050',
    type: 'city',
    parent: '대전',
  },
  {
    name: '울산',
    code: '26',
    type: 'province',
    parent: null,
  },
  {
    name: '울산 - 중구',
    code: '010',
    type: 'city',
    parent: '울산',
  },
  {
    name: '울산 - 남구',
    code: '020',
    type: 'city',
    parent: '울산',
  },
  {
    name: '울산 - 동구',
    code: '030',
    type: 'city',
    parent: '울산',
  },
  {
    name: '울산 - 북구',
    code: '040',
    type: 'city',
    parent: '울산',
  },
  {
    name: '울산 - 울주군',
    code: '510',
    type: 'city',
    parent: '울산',
  },
  {
    name: '세종시',
    code: '010',
    type: 'city',
    parent: '세종특별자치시',
  },
  {
    name: '경기도',
    code: '31',
    type: 'province',
    parent: null,
  },
  {
    name: '수원시',
    code: '010',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 수원시 장안구',
    code: '011',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 수원시 권선구',
    code: '012',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 수원시 팔달구',
    code: '013',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 수원시 영통구',
    code: '014',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 성남시',
    code: '020',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 성남시 수정구',
    code: '021',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 성남시 중원구',
    code: '022',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 성남시 분당구',
    code: '023',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 의정부시',
    code: '030',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 안양시',
    code: '040',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 안양시 만안구',
    code: '041',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 안양시 동안구',
    code: '042',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 부천시',
    code: '050',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 부천시 원미구',
    code: '051',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 부천시 소사구',
    code: '052',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 부천시 오정구',
    code: '053',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 광명시',
    code: '060',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 평택시',
    code: '070',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 동두천시',
    code: '080',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 안산시',
    code: '090',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 안산시 상록구',
    code: '091',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 안산시 단원구',
    code: '092',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 고양시',
    code: '100',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 고양시 덕양구',
    code: '101',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 고양시 일산동구',
    code: '103',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 고양시 일산서구',
    code: '104',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 과천시',
    code: '110',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 구리시',
    code: '120',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 남양주시',
    code: '130',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 오산시',
    code: '140',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 시흥시',
    code: '150',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 군포시',
    code: '160',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 의왕시',
    code: '170',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 하남시',
    code: '180',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 용인시',
    code: '190',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 용인시 처인구',
    code: '191',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 용인시 기흥구',
    code: '192',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 용인시 수지구',
    code: '193',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 파주시',
    code: '200',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 이천시',
    code: '210',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 안성시',
    code: '220',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 김포시',
    code: '230',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 화성시',
    code: '240',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 광주시',
    code: '250',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 양주시',
    code: '260',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 포천시',
    code: '270',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 여주시',
    code: '280',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 연천군',
    code: '550',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 가평군',
    code: '570',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '경기도 - 양평군',
    code: '580',
    type: 'city',
    parent: '경기도',
  },
  {
    name: '강원도',
    code: '32',
    type: 'province',
    parent: null,
  },
  {
    name: '강원도 - 춘천시',
    code: '010',
    type: 'city',
    parent: '강원도',
  },
  {
    name: '강원도 - 원주시',
    code: '020',
    type: 'city',
    parent: '강원도',
  },
  {
    name: '강원도 - 강릉시',
    code: '030',
    type: 'city',
    parent: '강원도',
  },
  {
    name: '강원도 - 동해시',
    code: '040',
    type: 'city',
    parent: '강원도',
  },
  {
    name: '강원도 - 태백시',
    code: '050',
    type: 'city',
    parent: '강원도',
  },
  {
    name: '강원도 - 속초시',
    code: '060',
    type: 'city',
    parent: '강원도',
  },
  {
    name: '강원도 - 삼척시',
    code: '070',
    type: 'city',
    parent: '강원도',
  },
  {
    name: '강원도 - 홍천군',
    code: '510',
    type: 'city',
    parent: '강원도',
  },
  {
    name: '강원도 - 횡성군',
    code: '520',
    type: 'city',
    parent: '강원도',
  },
  {
    name: '강원도 - 영월군',
    code: '530',
    type: 'city',
    parent: '강원도',
  },
  {
    name: '강원도 - 평창군',
    code: '540',
    type: 'city',
    parent: '강원도',
  },
  {
    name: '강원도 - 정선군',
    code: '550',
    type: 'city',
    parent: '강원도',
  },
  {
    name: '강원도 - 철원군',
    code: '560',
    type: 'city',
    parent: '강원도',
  },
  {
    name: '강원도 - 화천군',
    code: '570',
    type: 'city',
    parent: '강원도',
  },
  {
    name: '강원도 - 양구군',
    code: '580',
    type: 'city',
    parent: '강원도',
  },
  {
    name: '강원도 - 인제군',
    code: '590',
    type: 'city',
    parent: '강원도',
  },
  {
    name: '강원도 - 고성군',
    code: '600',
    type: 'city',
    parent: '강원도',
  },
  {
    name: '강원도 - 양양군',
    code: '610',
    type: 'city',
    parent: '강원도',
  },
  {
    name: '충북',
    code: '33',
    type: 'province',
    parent: null,
  },
  {
    name: '충북 - 충주시',
    code: '020',
    type: 'city',
    parent: '충북',
  },
  {
    name: '충북 - 제천시',
    code: '030',
    type: 'city',
    parent: '충북',
  },
  {
    name: '충북 - 청주시',
    code: '040',
    type: 'city',
    parent: '충북',
  },
  {
    name: '충북 - 청주시 상당구',
    code: '041',
    type: 'city',
    parent: '충북',
  },
  {
    name: '충북 - 청주시 서원구',
    code: '042',
    type: 'city',
    parent: '충북',
  },
  {
    name: '충북 - 청주시 흥덕구',
    code: '043',
    type: 'city',
    parent: '충북',
  },
  {
    name: '충북 - 청주시 청원구',
    code: '044',
    type: 'city',
    parent: '충북',
  },
  {
    name: '충북 - 보은군',
    code: '520',
    type: 'city',
    parent: '충북',
  },
  {
    name: '충북 - 옥천군',
    code: '530',
    type: 'city',
    parent: '충북',
  },
  {
    name: '충북 - 영동군',
    code: '540',
    type: 'city',
    parent: '충북',
  },
  {
    name: '충북 - 진천군',
    code: '550',
    type: 'city',
    parent: '충북',
  },
  {
    name: '충북 - 괴산군',
    code: '560',
    type: 'city',
    parent: '충북',
  },
  {
    name: '충북 - 음성군',
    code: '570',
    type: 'city',
    parent: '충북',
  },
  {
    name: '충북 - 단양군',
    code: '580',
    type: 'city',
    parent: '충북',
  },
  {
    name: '충북 - 증평군',
    code: '590',
    type: 'city',
    parent: '충북',
  },
  {
    name: '충남',
    code: '34',
    type: 'province',
    parent: null,
  },
  {
    name: '충남 - 천안시',
    code: '010',
    type: 'city',
    parent: '충남',
  },
  {
    name: '충남 - 천안시 동남구',
    code: '011',
    type: 'city',
    parent: '충남',
  },
  {
    name: '충남 - 천안시 서북구',
    code: '012',
    type: 'city',
    parent: '충남',
  },
  {
    name: '충남 - 공주시',
    code: '020',
    type: 'city',
    parent: '충남',
  },
  {
    name: '충남 - 보령시',
    code: '030',
    type: 'city',
    parent: '충남',
  },
  {
    name: '충남 - 아산시',
    code: '040',
    type: 'city',
    parent: '충남',
  },
  {
    name: '충남 - 서산시',
    code: '050',
    type: 'city',
    parent: '충남',
  },
  {
    name: '충남 - 논산시',
    code: '060',
    type: 'city',
    parent: '충남',
  },
  {
    name: '충남 - 계룡시',
    code: '070',
    type: 'city',
    parent: '충남',
  },
  {
    name: '충남 - 당진시',
    code: '080',
    type: 'city',
    parent: '충남',
  },
  {
    name: '충남 - 금산군',
    code: '510',
    type: 'city',
    parent: '충남',
  },
  {
    name: '충남 - 부여군',
    code: '530',
    type: 'city',
    parent: '충남',
  },
  {
    name: '충남 - 서천군',
    code: '540',
    type: 'city',
    parent: '충남',
  },
  {
    name: '충남 - 청양군',
    code: '550',
    type: 'city',
    parent: '충남',
  },
  {
    name: '충남 - 홍성군',
    code: '560',
    type: 'city',
    parent: '충남',
  },
  {
    name: '충남 - 예산군',
    code: '570',
    type: 'city',
    parent: '충남',
  },
  {
    name: '충남 - 태안군',
    code: '580',
    type: 'city',
    parent: '충남',
  },
  {
    name: '전북',
    code: '35',
    type: 'province',
    parent: null,
  },
  {
    name: '전북 - 전주시',
    code: '010',
    type: 'city',
    parent: '전북',
  },
  {
    name: '전북 - 전주시 완산구',
    code: '011',
    type: 'city',
    parent: '전북',
  },
  {
    name: '전북 - 전주시 덕진구',
    code: '012',
    type: 'city',
    parent: '전북',
  },
  {
    name: '전북 - 군산시',
    code: '020',
    type: 'city',
    parent: '전북',
  },
  {
    name: '전북 - 익산시',
    code: '030',
    type: 'city',
    parent: '전북',
  },
  {
    name: '전북 - 정읍시',
    code: '040',
    type: 'city',
    parent: '전북',
  },
  {
    name: '전북 - 남원시',
    code: '050',
    type: 'city',
    parent: '전북',
  },
  {
    name: '전북 - 김제시',
    code: '060',
    type: 'city',
    parent: '전북',
  },
  {
    name: '전북 - 완주군',
    code: '510',
    type: 'city',
    parent: '전북',
  },
  {
    name: '전북 - 진안군',
    code: '520',
    type: 'city',
    parent: '전북',
  },
  {
    name: '전북 - 무주군',
    code: '530',
    type: 'city',
    parent: '전북',
  },
  {
    name: '전북 - 장수군',
    code: '540',
    type: 'city',
    parent: '전북',
  },
  {
    name: '전북 - 임실군',
    code: '550',
    type: 'city',
    parent: '전북',
  },
  {
    name: '전북 - 순창군',
    code: '560',
    type: 'city',
    parent: '전북',
  },
  {
    name: '전북 - 고창군',
    code: '570',
    type: 'city',
    parent: '전북',
  },
  {
    name: '전북 - 부안군',
    code: '580',
    type: 'city',
    parent: '전북',
  },
  {
    name: '전남',
    code: '36',
    type: 'province',
    parent: null,
  },
  {
    name: '전남 - 목포시',
    code: '010',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 여수시',
    code: '020',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 순천시',
    code: '030',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 나주시',
    code: '040',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 광양시',
    code: '060',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 담양군',
    code: '510',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 곡성군',
    code: '520',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 구례군',
    code: '530',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 고흥군',
    code: '550',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 보성군',
    code: '560',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 화순군',
    code: '570',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 장흥군',
    code: '580',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 강진군',
    code: '590',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 해남군',
    code: '600',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 영암군',
    code: '610',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 무안군',
    code: '620',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 함평군',
    code: '630',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 영광군',
    code: '640',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 장성군',
    code: '650',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 완도군',
    code: '660',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 진도군',
    code: '670',
    type: 'city',
    parent: '전남',
  },
  {
    name: '전남 - 신안군',
    code: '680',
    type: 'city',
    parent: '전남',
  },
  {
    name: '경북',
    code: '37',
    type: 'province',
    parent: null,
  },
  {
    name: '경북 - 포항시',
    code: '010',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 포항시 남구',
    code: '011',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 포항시 북구',
    code: '012',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 경주시',
    code: '020',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 김천시',
    code: '030',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 안동시',
    code: '040',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 구미시',
    code: '050',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 영주시',
    code: '060',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 영천시',
    code: '070',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 상주시',
    code: '080',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 문경시',
    code: '090',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 경산시',
    code: '100',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 의성군',
    code: '520',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 청송군',
    code: '530',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 영양군',
    code: '540',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 영덕군',
    code: '550',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 청도군',
    code: '560',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 고령군',
    code: '570',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 성주군',
    code: '580',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 칠곡군',
    code: '590',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 예천군',
    code: '600',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 봉화군',
    code: '610',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 울진군',
    code: '620',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경북 - 울릉군',
    code: '630',
    type: 'city',
    parent: '경북',
  },
  {
    name: '경남',
    code: '38',
    type: 'province',
    parent: null,
  },
  {
    name: '경남 - 진주시',
    code: '030',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 통영시',
    code: '050',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 사천시',
    code: '060',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 김해시',
    code: '070',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 밀양시',
    code: '080',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 거제시',
    code: '090',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 양산시',
    code: '100',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 창원시',
    code: '11',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 창원시 의창구',
    code: '111',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 창원시 성산구',
    code: '112',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 창원시 마산합포구',
    code: '113',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 창원시 마산회원구',
    code: '114',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 창원시 진해구',
    code: '115',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 의령군',
    code: '510',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 함안군',
    code: '520',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 창녕군',
    code: '530',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 고성군',
    code: '540',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 남해군',
    code: '550',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 하동군',
    code: '560',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 산청군',
    code: '570',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 함양군',
    code: '580',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 거창군',
    code: '590',
    type: 'city',
    parent: '경남',
  },
  {
    name: '경남 - 합천군',
    code: '600',
    type: 'city',
    parent: '경남',
  },
  {
    name: '제주도',
    code: '39',
    type: 'province',
    parent: null,
  },
];
